name: ARM Linux (gcc)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: sudo apt-get install -y libdrm-dev

      - name: Setup gcc
        uses: egor-tensin/setup-gcc@v1

      - name: Build and Test
        run: ./scripts/feature-tests.shell
