name: code-style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install clang-format

      - name: Display clang-format version
        run: clang-format --version

      - name: Run clang-format
        run: ./code_style_check.sh
        shell: bash
